Repository nextcloud/user_oidc, pull requests merged in 2022-07, with the labels that each got.

#444 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#451 Handle Ldap deleted users with non-auto provisioning
  lib/Controller/LoginController.php
  lib/Service/LdapService.php
  lib/User/Backend.php
Labels: bug, security

#450 Add admin endpoint to create user for pre-provisioning
  appinfo/routes.php
  lib/Controller/ApiController.php
Labels: enhancement
