Repository nextcloud/user_oidc, pull requests merged in 2022-04, with the labels that each got.

#407 Add new provider setting to request extra claims
  lib/Command/UpsertProvider.php
  lib/Controller/LoginController.php
  lib/Service/ProviderService.php
  src/components/SettingsForm.vue
  tests/unit/Service/ProviderServiceTest.php
Labels: enhancement, php

#412 Cache user object when checking existance
  lib/Db/UserMapper.php
Labels: performance

#425 Ensure that a remember me cookie is created
  lib/Controller/LoginController.php
Labels: bug

#426 Ignore more stuff in .nextcloudignore
  .nextcloudignore
Labels: enhancement
