Repository nextcloud/user_oidc, pull requests merged in 2022-02, with the labels that each got.

#379 Updating fixup.yml workflow from template
  .github/workflows/fixup.yml
Labels: dependencies

#382 Avoid using Php 7.3 with server master
  .github/workflows/phpunit.yml
Labels: enhancement

#372 New system config to disable SelfEncodedValidator bearer token validator
  README.md
  lib/User/Backend.php
Labels: enhancement, security, php

#385 Move to IBootstrap
  appinfo/app.php
  appinfo/info.xml
  lib/AppInfo/Application.php
Labels: enhancement

#381 Dispatch new event when a bearer token is validated
  lib/Event/TokenValidatedEvent.php
  lib/User/Backend.php
Labels: enhancement, php
