Repository nextcloud/user_oidc, pull requests merged in 2022-08, with the labels that each got.

#464 Implement backchannel logout
  README.md
  appinfo/info.xml
  appinfo/routes.php
  lib/Controller/LoginController.php
  lib/Cron/CleanupSessions.php
  lib/Db/Session.php
  lib/Db/SessionMapper.php
  lib/Migration/Version01021Date20220719114355.php
  src/components/AdminSettings.vue
Labels: enhancement

#469 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#486 Use node 16
  .github/workflows/appstore-build-publish.yml
  .github/workflows/lint.yml
  .github/workflows/node.yml
  package-lock.json
  package.json
  src/components/AdminSettings.vue
  src/components/SettingsForm.vue
  src/main-settings.js
Labels: enhancement

#495 Enforce https
  .github/workflows/integration.yml
  lib/Controller/LoginController.php
Labels: enhancement, security
