Repository nextcloud/user_oidc, pull requests merged in 2024-10, with the labels that each got.

#954 New system config flag to disable user creation in soft auto provisioning
  .github/workflows/integration.yml
  README.md
  lib/Service/ProvisioningService.php
  tests/unit/Service/ProvisioningServiceTest.php
Labels: enhancement, 3. to review

#955 Backchannel logout endpoint should only return 200 or 400
  lib/Controller/LoginController.php
Labels: enhancement, 3. to review

#958 Use correct userId when getting user folder in provisioning endpoint
  lib/Controller/ApiController.php
Labels: bug, 3. to review

#961 Prevent redirecting to an absolute URL after login
  lib/Controller/LoginController.php
Labels: enhancement, 3. to review

#948 Fix/947/empty address
  lib/Service/ProvisioningService.php
Labels: bug

#969 fix: Ensure $providerClientId is declare
  lib/User/Validator/SelfEncodedValidator.php
Labels: bug, php
