Repository nextcloud/user_oidc, pull requests merged in 2024-12, with the labels that each got.

#990 Use absolute paths instead of relative paths
  lib/AppInfo/Application.php
Labels: bug, 3. to review

#1008 fix: Handle redirect URL containing a ':'
  lib/Controller/LoginController.php
Labels: bug, php, 3. to review

#1014 Make the email match optional when searching for a user or a display name
  README.md
  lib/Db/UserMapper.php
  tests/unit/Db/UserMapperTest.php
Labels: enhancement, 3. to review

#1016 chore(CI): Updating reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies
