Repository nextcloud/user_oidc, pull requests merged in 2025-02, with the labels that each got.

#1045 docs: Replace broken jumpstart docs link
  README.md
Labels: bug, documentation, 3. to review

#1046 Map the user language
  lib/Command/UpsertProvider.php
  lib/Service/ProviderService.php
  lib/Service/ProvisioningService.php
  src/components/SettingsForm.vue
  tests/unit/Service/ProviderServiceTest.php
  tests/unit/Service/ProvisioningServiceTest.php
Labels: enhancement, 3. to review

#1035 fix '"kid" invalid, unable to lookup correct key' when keys are rotated
  lib/Controller/LoginController.php
  lib/Service/DiscoveryService.php
Labels: feedback-requested
