Repository nextcloud/user_oidc, pull requests merged in 2025-01, with the labels that each got.

#1019 fix: Avoid slow queries in scenarios where we do not need a search
  lib/Controller/LoginController.php
  lib/Service/LdapService.php
  lib/Service/ProvisioningService.php
Labels: bug

#1011 Add global scale (gss) support
  lib/Controller/LoginController.php
  lib/Service/ProvisioningService.php
  lib/User/Backend.php
  tests/unit/Service/ProvisioningServiceTest.php
Labels: enhancement, 3. to review

#979 Adjust provisioning service to correctly update the display name on login
  lib/Controller/ApiController.php
  lib/Controller/OcsApiController.php
  lib/Service/ProvisioningService.php
Labels: bug, 3. to review

#1025 fix(token-refresh): handle missing attributes in login token
  docs/token_exchange.md
  lib/Controller/LoginController.php
  lib/Model/Token.php
  lib/Service/TokenService.php
Labels: bug, 3. to review
