Repository nextcloud/user_oidc, pull requests merged in 2025-06, with the labels that each got.

#1123 Set the gss session data in the controller rather than in the service
  lib/Controller/LoginController.php
  lib/Service/ProvisioningService.php
  lib/User/Provisioning/SelfEncodedTokenProvisioning.php
Labels: bug, 3. to review

#1141 Migrate to vue 3 and nextcloud/vue 9
  .eslintrc.cjs
  .eslintrc.js
  package-lock.json
  package.json
  src/components/AdminSettings.vue
  src/components/SettingsForm.vue
  src/main-settings.js
  stylelint.config.cjs
  stylelint.config.js
Labels: technical debt, 3. to review

#1146 Use outlined icons
  src/components/AdminSettings.vue
Labels: enhancement

#1148 ci: update reuse.yml workflow from template
  .github/workflows/reuse.yml
Labels: dependencies

#1144 Add provider deletion confirmation
  src/components/AdminSettings.vue
Labels: enhancement, 3. to review
